# -*- coding: utf-8 -*-

#  Copyright (c) 2022 github.com/shadowdog9500 .
#  License: MIT

# Form implementation generated from reading ui file 'src/ui/patcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonFileSelect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonFileSelect.setGeometry(QtCore.QRect(10, 10, 121, 28))
        self.pushButtonFileSelect.setObjectName("pushButtonFileSelect")
        self.pushButtonLoadPatchFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoadPatchFile.setGeometry(QtCore.QRect(150, 10, 93, 28))
        self.pushButtonLoadPatchFile.setObjectName("pushButtonLoadPatchFile")
        self.plainTextEditConsole = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEditConsole.setGeometry(QtCore.QRect(10, 310, 761, 261))
        self.plainTextEditConsole.setReadOnly(True)
        self.plainTextEditConsole.setObjectName("plainTextEditConsole")
        self.plainTextEditDescriptionBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEditDescriptionBox.setGeometry(QtCore.QRect(330, 60, 441, 231))
        self.plainTextEditDescriptionBox.setReadOnly(True)
        self.plainTextEditDescriptionBox.setObjectName("plainTextEditDescriptionBox")
        self.listViewPatchList = QtWidgets.QListView(self.centralwidget)
        self.listViewPatchList.setGeometry(QtCore.QRect(10, 60, 281, 231))
        self.listViewPatchList.setObjectName("listViewPatchList")
        self.pushButtonPatchBinary = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPatchBinary.setGeometry(QtCore.QRect(680, 10, 93, 28))
        self.pushButtonPatchBinary.setObjectName("pushButtonPatchBinary")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Patch Selector"))
        self.pushButtonFileSelect.setText(_translate("MainWindow", "Select Binary File"))
        self.pushButtonLoadPatchFile.setText(_translate("MainWindow", "Load patch file"))
        self.pushButtonPatchBinary.setText(_translate("MainWindow", "Patch File"))
