# -*- coding: utf-8 -*-

#  Copyright (c) 2022 github.com/shadowdog9500 .
#  License: MIT

# Form implementation generated from reading ui file 'src/ui/patcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonFileSelect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonFileSelect.setObjectName("pushButtonFileSelect")
        self.gridLayout.addWidget(self.pushButtonFileSelect, 0, 0, 1, 1)
        self.pushButtonLoadPatchFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoadPatchFile.setObjectName("pushButtonLoadPatchFile")
        self.gridLayout.addWidget(self.pushButtonLoadPatchFile, 0, 1, 1, 1)
        self.pushButtonPatchBinary = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPatchBinary.setObjectName("pushButtonPatchBinary")
        self.gridLayout.addWidget(self.pushButtonPatchBinary, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.listViewPatchList = QtWidgets.QListView(self.centralwidget)
        self.listViewPatchList.setObjectName("listViewPatchList")
        self.gridLayout.addWidget(self.listViewPatchList, 2, 0, 1, 2)
        self.plainTextEditDescriptionBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEditDescriptionBox.setReadOnly(True)
        self.plainTextEditDescriptionBox.setObjectName("plainTextEditDescriptionBox")
        self.gridLayout.addWidget(self.plainTextEditDescriptionBox, 2, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.plainTextEditConsole = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEditConsole.setReadOnly(True)
        self.plainTextEditConsole.setObjectName("plainTextEditConsole")
        self.gridLayout.addWidget(self.plainTextEditConsole, 4, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Patch Selector"))
        self.pushButtonFileSelect.setText(_translate("MainWindow", "Select Binary File"))
        self.pushButtonLoadPatchFile.setText(_translate("MainWindow", "Load patch file"))
        self.pushButtonPatchBinary.setText(_translate("MainWindow", "Patch File"))
        self.label.setText(_translate("MainWindow", "Patch List:"))
        self.label_2.setText(_translate("MainWindow", "Patch Metadata:"))
        self.label_3.setText(_translate("MainWindow", "Console:"))
